version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 9000:27017


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: localhost
      DATABASE_PORT: 9000
      DATABASE_NAME: continer-app
      DATABASE_INIT: "true"
    depends_on:
      - mongodb
    network_mode: "host"
